// TF-DEV: conditions.html 전용.
function computerChatMessage(role,text){return '<div class="conversation-turn '+(role==='user'?'user':'')+'"><span class="conversation-label">'+(role==='user'?'나':'TrueFit')+'</span><div class="conversation-bubble">'+esc(text)+'</div></div>'}
function tfQuestionChips(q){if(!q||!Array.isArray(q.options)||!q.options.length)return '';const multi=q.select==='multi';return '<div class="conversation-options" role="group" aria-label="'+esc(q.text||'선택지')+'">'+q.options.map(o=>'<button type="button" class="conversation-option" data-answer-question="'+esc(q.id)+'" data-answer-value="'+esc(o.value)+'"'+(multi?' data-answer-multi aria-pressed="false"':'')+'>'+esc(o.label??o.value)+'</button>').join('')+(multi?'<button type="button" class="conversation-option primary-option" data-answer-submit="'+esc(q.id)+'">선택 완료</button>':'')+'</div>'}
function conditionsPage(){if(!tfPlan.listId)return go('category');const s=tfPlan.condition;if(!s||s.list_id!==tfPlan.listId){tfLoadThen(conditionsPage,1,()=>TF_PLAN.condition(tfPlan.listId).then(data=>{tfPlan.condition=tfRequire(data)}));return}if(!s.category)return go('category');
 const pc=tfUiCategory(s.category)==='pc',rawMessages=Array.isArray(s.messages)?s.messages:[],resetMark=tfResetMark(tfPlan.listId),messages=resetMark&&resetMark.count<=rawMessages.length?[...(resetMark.text?[{role:'assistant',text:resetMark.text}]:[]),...rawMessages.slice(resetMark.count)]:rawMessages,started=messages.some(m=>m.role==='user'),complete=!!s.can_recommend;
 const transcript=messages.map(m=>computerChatMessage(m.role,m.text)).join('');
 const attach=s.accepts_spec_file?'<label class="spec-file-button" for="tf-spec-file">＋ 사양 파일<input class="spec-file-input" id="tf-spec-file" type="file" accept=".txt,.json,.csv,.md,.log,.nfo,.xml,text/plain,application/json"></label>':'';
 // TF-DEV: 사양 파일은 서버에서 인식하도록 결정(2026-09-11) → 안내 문구 변경
 const fileNote=s.accepts_spec_file?'<p class="local-file-note">사양 인식을 위해 첨부한 파일 내용을 서버로 전송합니다. 텍스트 기반 사양 파일(1MB 이하)을 지원합니다.</p>':'';
 const composer='<div class="conversation-current">'+(complete?'':tfQuestionChips(s.next_question))+'<form id="tf-chat-form"><div class="chat-compose-grid '+(attach?'':'no-file')+'">'+attach+'<input id="tf-chat-input" name="message" type="text" aria-label="'+(pc?'컴퓨터':'육아용품')+' 조건 대화 입력" placeholder="'+(complete?'추가 조건이나 변경할 내용을 입력해 주세요':started?'답변을 입력해 주세요':pc?'필요한 컴퓨터에 대해 먼저 이야기해 주세요':'필요한 육아용품에 대해 먼저 이야기해 주세요')+'" maxlength="500" autocomplete="off" required><button class="btn strong" type="submit">전송 →</button></div>'+fileNote+'<p id="tf-chat-error" class="error" role="alert"></p></form></div>';
 const completion=complete?'<div class="conversation-complete"><h2>조건을 모두 확인했어요.</h2><p>추가 조건이나 변경할 내용이 있다면 아래 대화창에 입력해 주세요.</p><button class="btn strong" type="button" data-plan-recommend>이 조건으로 추천 보기 →</button></div>':'';
 const summary=(s.fields||[]).map(f=>{const answered=f.status!=='missing'&&f.display!==null&&f.display!==undefined&&f.display!=='';return '<div><dt>'+esc(f.label)+'</dt><dd class="'+(answered?'spec-summary-text':'empty')+'" data-summary="'+esc(f.key)+'">'+(answered?esc(f.display)+(f.status==='assumed'?' <span class="tag gray">추정</span>':''):'아직 확인되지 않았어요')+'</dd>'+(answered&&f.editable?'<button class="summary-edit" type="button" data-edit-field="'+esc(f.key)+'">수정하기</button>':'')+'</div>'}).join('');
 const summaryPanel=started?'<aside class="condition-summary" aria-live="polite"><span class="condition-kicker">YOUR CHOICES</span><h2>선택한 조건 확인</h2><dl class="condition-summary-list">'+summary+'</dl><p class="summary-ready">'+(complete?'답변이 모두 반영됐습니다. 추천 결과로 이동할 수 있어요.':'챗봇이 부족한 정보를 이어서 질문합니다.')+'</p></aside>':'';
 const resetButton=started?'<button class="btn computer-reset" type="button" data-plan-reset>대화 다시 시작</button>':'';
 shell('<div class="condition-layout '+(started?'':'is-start')+'"><main class="condition-main"><section class="condition-card conversation-card"><h1 tabindex="-1">'+(pc?'어떤 컴퓨터가 필요한가요?':'어떤 육아용품이 필요한가요?')+'</h1><div class="conversation-feed">'+transcript+completion+composer+'</div><div style="margin-top:28px"><button class="btn" type="button" data-action="category">← 카테고리 변경</button>'+resetButton+'</div></section></main>'+summaryPanel+'</div>',1);
 flow.querySelector('#tf-chat-input')?.focus({preventScroll:true})}
function scrollConditionConversation(){const target=flow.querySelector('.conversation-current')||flow.querySelector('.conversation-complete');if(!target)return;requestAnimationFrame(()=>requestAnimationFrame(()=>{const rect=target.getBoundingClientRect();if(rect.top>=0&&rect.bottom<=window.innerHeight)return;const turns=[...flow.querySelectorAll('.conversation-turn')],anchor=turns[Math.max(0,turns.length-3)]||target,anchorRect=anchor.getBoundingClientRect(),top=Math.max(0,window.scrollY+anchorRect.top-window.innerHeight*.05);window.scrollTo({top,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}))}
// 조건 대화 요청 공통: 요청 중 중복 방지 → 응답(ConditionState)으로 화면 갱신. 조건이 바뀌면 기존 추천 결과는 무효.
async function tfConditionAction(task,{button=null,busyLabel='보내는 중…',errorTarget='#tf-chat-error',invalidateResult=true}={}){if(tfPlan.busy)return false;const listId=tfPlan.listId;tfPlan.busy=true;tfBusy(button,true,busyLabel);try{const data=tfRequire(await task(listId));if(listId!==tfPlan.listId)return false;tfPlan.condition=data;if(invalidateResult){tfPlan.result=null;tfStopPoll()}conditionsPage();scrollConditionConversation();return true}catch(err){if(tfListGone(err))return false;const target=flow.querySelector(errorTarget);if(target)target.textContent=tfAuthErrorMessage(err);else toast(tfAuthErrorMessage(err));tfBusy(button,false);return false}finally{tfPlan.busy=false}}
function tfReadSpecFile(input){const file=input.files&&input.files[0];if(!file)return;const error=flow.querySelector('#tf-chat-error');if(!/\.(txt|json|csv|md|log|nfo|xml)$/i.test(file.name)){if(error)error.textContent='TXT, JSON, CSV, MD, LOG, NFO 또는 XML 파일을 첨부해 주세요.';input.value='';return}if(file.size>1024*1024){if(error)error.textContent='1MB 이하의 텍스트 기반 사양 파일을 첨부해 주세요.';input.value='';return}const reader=new FileReader();reader.onload=()=>tfConditionAction(listId=>TF_PLAN.specFile(listId,file.name,String(reader.result||'')));reader.onerror=()=>{if(error)error.textContent='파일을 읽지 못했습니다. 다른 텍스트 파일을 선택해 주세요.'};reader.readAsText(file)}
async function tfResetConversation(button){if(tfPlan.busy)return;if(!window.confirm('이전 대화 내용이 모두 사라지고 처음부터 다시 시작해요. 계속할까요?'))return;const listId=tfPlan.listId;tfPlan.busy=true;tfBusy(button,true,'초기화 중…');try{const data=tfRequire(await TF_PLAN.reset(listId));if(listId!==tfPlan.listId)return;tfSetResetMark(listId,Array.isArray(data.messages)?data.messages.length:0,data.next_question?data.next_question.text:'');tfPlan.condition=data;tfPlan.result=null;tfStopPoll();conditionsPage();scrollConditionConversation()}catch(err){if(tfListGone(err))return;toast(tfAuthErrorMessage(err));tfBusy(button,false)}finally{tfPlan.busy=false}}
async function tfStartRecommend(button,strategy){if(tfPlan.busy)return;const listId=tfPlan.listId;tfPlan.busy=true;tfBusy(button,true,'추천을 시작하는 중…');try{await TF_PLAN.recommend(listId,strategy);if(listId!==tfPlan.listId)return;tfPlan.result=null;tfPlan.resultMessages=[];tfPlan.listsLoaded=false;go('results')}catch(err){tfBusy(button,false);if(tfListGone(err))return;if(err.code==='conditions_incomplete'){toast('아직 확인되지 않은 조건이 있어요. 대화로 조건을 채워 주세요.');conditionsPage();return}if(err.code==='run_in_progress'){go('results');return}toast(tfAuthErrorMessage(err))}finally{tfPlan.busy=false}}
conditionsPage();
flow.addEventListener('change',e=>{if(e.target.id==='tf-spec-file')tfReadSpecFile(e.target)});
flow.addEventListener('click',e=>{
 const answerValue=e.target.closest('[data-answer-value]');
 if(answerValue){if(answerValue.hasAttribute('data-answer-multi')){const pressed=answerValue.getAttribute('aria-pressed')!=='true';answerValue.setAttribute('aria-pressed',String(pressed));answerValue.classList.toggle('primary-option',pressed);return}tfConditionAction(listId=>TF_PLAN.answer(listId,answerValue.dataset.answerQuestion,[answerValue.dataset.answerValue]),{button:answerValue});return}
 const answerSubmit=e.target.closest('[data-answer-submit]');
 if(answerSubmit){const selected=[...flow.querySelectorAll('[data-answer-multi][aria-pressed="true"]')].map(x=>x.dataset.answerValue),error=flow.querySelector('#tf-chat-error');if(!selected.length){if(error)error.textContent='하나 이상 선택해 주세요.';return}tfConditionAction(listId=>TF_PLAN.answer(listId,answerSubmit.dataset.answerSubmit,selected),{button:answerSubmit});return}
 const editField=e.target.closest('[data-edit-field]');
 if(editField){tfConditionAction(listId=>TF_PLAN.clearSlot(listId,editField.dataset.editField),{button:editField,busyLabel:'수정 중…'});return}
 if(e.target.closest('[data-plan-reset]')){tfResetConversation(e.target);return}
 const recommend=e.target.closest('[data-plan-recommend]');
 if(recommend){tfStartRecommend(recommend);return}
});
flow.addEventListener('submit',e=>{if(e.target.id!=='tf-chat-form')return;e.preventDefault();const answer=String(new FormData(e.target).get('message')||'').trim();if(!answer)return;tfConditionAction(listId=>TF_PLAN.message(listId,answer),{button:e.target.querySelector('button[type=submit]')})});
