// TF-DEV: category/conditions/results/logs/confirm/report 6개 페이지가 공유하는 뼈대.
// 사이드바·단계 표시줄·장바구니 이름변경삭제·추천 결과 공용 조각(리뷰 지표, 후보 비교, 폴링 등)을 담는다.
// 페이지별 화면(js/pages/*.js)은 이 파일 다음에 로드되어 shell()/sidebar() 등을 그대로 사용한다.

function tfRefreshLists(){if(tfPlan.listsLoading)return;tfPlan.listsLoading=true;TF_PLAN.lists().then(data=>{tfPlan.lists=Array.isArray(data&&data.items)?data.items:[];tfPlan.listsError=null}).catch(err=>{tfPlan.lists=tfPlan.lists||[];tfPlan.listsError=err}).finally(()=>{tfPlan.listsLoading=false;tfPlan.listsLoaded=true;const aside=flow.querySelector('.planner-sidebar');if(aside)aside.outerHTML=sidebar()})}
function sidebar(){if(!tfPlan.listsLoaded&&!tfPlan.listsLoading)setTimeout(tfRefreshLists,0);const session=readAuthSession(),sideTitle=session?esc(session.name||'회원')+'님 장바구니':'내 장바구니';let collapsed=false;try{collapsed=localStorage.getItem(SIDEBAR_STORE)==='1'}catch{}const items=tfPlan.lists||[];let baskets;if(!tfPlan.listsLoaded)baskets='<p class="muted" style="font-size:12px;margin:4px 8px">장바구니를 불러오는 중…</p>';else if(tfPlan.listsError&&!items.length)baskets='<p class="muted" style="font-size:12px;margin:4px 8px">'+esc(tfAuthErrorMessage(tfPlan.listsError))+'</p>';else baskets=items.map(list=>{const id=esc(list.list_id),route=tfStageRoute(list.stage),name=esc(list.name||'새 장바구니');return '<div class="planner-saved-item" data-basket-item="'+id+'"><a class="'+(list.list_id===tfPlan.listId?'current':'')+'" href="'+tfHref(route)+'" data-open-basket="'+id+'" data-basket-route="'+route+'">'+name+'</a><button class="basket-rename-button" type="button" data-basket-rename="'+id+'" aria-label="'+name+' 이름 변경" title="장바구니 이름 변경">✎</button><button class="basket-delete-button" type="button" data-basket-delete="'+id+'" aria-label="'+name+' 삭제" title="장바구니 삭제">×</button><form class="basket-name-form" data-basket-name-form="'+id+'" hidden><input name="basketName" value="'+name+'" maxlength="60" aria-label="장바구니 이름" required><button type="submit">저장</button><button class="basket-name-cancel" type="button" data-basket-cancel>취소</button></form></div>'}).join('')||'<a href="category.html">아직 저장된 장바구니가 없어요</a>';return '<aside class="planner-sidebar '+(collapsed?'is-collapsed':'')+'"><button class="sidebar-toggle" type="button" data-sidebar-toggle aria-label="'+(collapsed?'사이드바 열기':'사이드바 접기')+'" aria-expanded="'+String(!collapsed)+'" title="'+(collapsed?'사이드바 열기':'사이드바 접기')+'">‹</button><a class="planner-home" href="index.html"><span class="planner-brand-full">TrueFit.</span><span class="planner-brand-short">TF</span></a><a class="planner-new" href="category.html" data-new-basket><span class="planner-new-full">＋ 새 장바구니</span><span class="planner-new-short">＋</span></a><div><span class="planner-side-title">'+sideTitle+'</span><nav class="planner-saved" aria-label="내 장바구니">'+baskets+'</nav></div><p class="planner-side-note">장바구니는 서버에 저장됩니다.<br>로그인하지 않으면 이 브라우저에서만 이어볼 수 있어요.</p></aside>'}
function flowAccountNav(){const session=readAuthSession();if(!session)return '<nav class="mini-nav flow-account-nav" aria-label="회원 메뉴"><a href="login.html">로그인</a><a href="signup.html">회원가입</a></nav>';return '<nav class="mini-nav flow-account-nav" aria-label="회원 메뉴"><span class="account-user-name">'+esc(session.name||'회원')+'님</span><div class="service-menu mypage-menu"><button type="button" class="service-trigger" aria-haspopup="true">마이페이지</button><div class="service-dropdown" aria-label="마이페이지 메뉴"><a href="'+tfHref(tfPlanRoute())+'">장바구니</a><a href="account.html">회원정보 수정</a><a href="#" data-flow-account-logout>로그아웃</a></div></div></nav>'}
function steps(i){const summary=tfListSummary(),result=tfPlan.result,defs=[['카테고리','category',true],['조건 입력','conditions',!!tfPlan.listId],['추천 결과','results',!!(result&&['running','done'].includes(result.status))||['results','report'].includes(summary?.stage)],['리스트 확정','confirm',!!(result&&result.totals&&result.totals.selected_units)],['리포트','report',!!tfPlan.report||summary?.stage==='report']];return `<ol class="flow-steps" aria-label="장바구니 만들기 단계">${defs.map(([label,route,enabled],n)=>{const text=`0${n+1} ${label}`;return `<li class="${n===i?'active ':''}${enabled?'':'disabled'}" ${n===i?'aria-current="step"':''}>${enabled?`<a href="${tfHref(route)}">${text}</a>`:`<span aria-disabled="true">${text}</span>`}</li>`}).join('')}</ol>`}
function shell(body,i){const notice=(tfPlan.result&&tfPlan.result.data_notice)||(tfPlan.report&&tfPlan.report.data_notice)||'';flow.innerHTML=`<div class="planner-shell">${sidebar()}<div class="planner-work"><div class="flow-wrap"><div class="flow-top"><a href="index.html" class="flow-logo">← TrueFit</a>${flowAccountNav()}</div>${steps(i)}${notice?`<div class="demo-note">${esc(notice)}</div>`:''}${body}</div></div></div>`;const h=flow.querySelector('h1');if(h)h.focus({preventScroll:true})}
// 데이터를 불러와야 여는 화면 공용: renderFn — 불러오기 끝나면 다시 그릴 함수(대개 이 페이지 함수 자신)
function tfLoadThen(renderFn,stepIndex,task){const seq=++tfPlan.seq;shell(tfStatusPanel('불러오는 중이에요…'),stepIndex);task().then(()=>{if(seq===tfPlan.seq)renderFn()}).catch(err=>{if(seq!==tfPlan.seq)return;if(tfListGone(err))return;shell(tfStatusPanel('정보를 불러오지 못했어요.',tfAuthErrorMessage(err),'<button class="btn strong" type="button" data-reload>다시 시도</button>'),stepIndex)})}
function createNewBasket(){tfSelectList(null);go('category')}

// ── 추천 결과 공용 조각 (results.html · logs.html · confirm.html · report.html 에서 사용) ──
const TF_TIMING_LABELS={now:'지금',soon:'곧 (1~3개월)',later:'나중'};
function partThumbnail(label,imageUrl){return imageUrl?'<span class="part-thumb" role="img" aria-label="'+esc(label)+' 제품 이미지"><img src="'+esc(imageUrl)+'" alt="" style="width:100%;height:100%;object-fit:contain"></span>':'<span class="part-thumb" role="img" aria-label="'+esc(label)+' 제품 이미지 영역"><span class="part-thumb-art" aria-hidden="true"></span><small>'+esc(label)+' 이미지</small></span>'}
function tfLlmText(field,pending='문장을 만드는 중이에요…',failed='문장을 만들지 못했어요.'){if(!field)return '';if(field.status==='ready')return field.text||field.headline||'';return field.status==='failed'?failed:pending}
function tfReviewMetric(review){if(!review)return '<span>리뷰 정보 없음</span>';return '<span>리뷰 <strong>'+Number(review.total_count||0).toLocaleString('ko-KR')+'건</strong></span><span class="review-divider">·</span><span class="review-filtered">조작 의심 '+Math.round((review.excluded_ratio||0)*100)+'% 제외</span><span class="review-divider">·</span><span>실사용 평점 <strong>'+(review.rating_refined!=null?Number(review.rating_refined).toFixed(1):'—')+'</strong></span>'}
function tfReviewButton(item,extraClass=''){return '<button class="review-score-trigger '+extraClass+'" type="button" data-plan-review="'+esc(item.item_id)+'" aria-label="'+esc(item.slot_label)+' 리뷰와 근거 상세 보기">'+tfReviewMetric(item.review)+'<span class="review-arrow" aria-hidden="true">↗</span></button>'}
function tfResultPending(result){if(!result)return false;if(result.status==='running')return true;const fields=[result.verification,result.explanation,...(result.items||[]).flatMap(item=>[item.reason,item.checks])];return fields.some(field=>field&&field.status==='pending')}
// renderFn — 새 결과를 받은 뒤 다시 그릴 함수. results.html은 resultsPage({preserve:true}), logs.html은 logsPage.
function tfSchedulePoll(renderFn){tfStopPoll();if(!tfResultPending(tfPlan.result))return;const listId=tfPlan.listId;tfPlan.pollTimer=setTimeout(async()=>{if(listId!==tfPlan.listId)return;if(flow.querySelector('.result-overlay[open]')){tfSchedulePoll(renderFn);return}try{tfPlan.result=tfRequire(await TF_PLAN.result(listId));if(listId!==tfPlan.listId)return;renderFn()}catch(err){if(!tfListGone(err))tfPlan.pollTimer=setTimeout(()=>tfSchedulePoll(renderFn),4000)}},1500)}
function tfLoadResult(renderFn,stepIndex){tfLoadThen(renderFn,stepIndex,()=>TF_PLAN.result(tfPlan.listId).then(data=>{tfPlan.result=tfRequire(data)}).catch(err=>{if(err.status===404&&err.code==='not_found'){tfPlan.result={list_id:tfPlan.listId,status:'none'};return}throw err}))}
function tfBudgetText(result){const totals=result.totals||{},budget=Number(result.budget_max||0);if(!budget)return '';return '예산 '+won(budget)+'<br>'+(totals.over_budget?'<span class="error">예산을 '+won(Math.abs(Number(totals.budget_remaining||0)))+' 초과했어요.</span>':won(Number(totals.budget_remaining||0))+' 남아요.')}
function tfResultCart(result){const items=(result.items||[]).filter(item=>item.selected),totals=result.totals||{};return '<aside class="result-cart"><h2>나의 장바구니 <span class="tag">'+Number(totals.selected_units||0)+'</span></h2><div class="result-cart-list">'+items.map(item=>{const qty=Math.max(1,Number(item.qty)||1),id=esc(item.item_id),label=esc(item.slot_label);return '<div class="result-cart-item"><div class="result-cart-item-head"><span>'+label+'</span><strong>'+esc(item.product?.name)+'</strong></div><button class="cart-remove" type="button" data-plan-remove="'+id+'" aria-label="'+label+' 장바구니에서 삭제">×</button><div class="result-cart-item-bottom"><span class="cart-qty" aria-label="'+label+' 수량"><button type="button" data-plan-qty="-1" data-plan-item="'+id+'" aria-label="수량 줄이기" '+(qty<=1?'disabled':'')+'>−</button><output aria-label="현재 수량">'+qty+'</output><button type="button" data-plan-qty="1" data-plan-item="'+id+'" aria-label="수량 늘리기" '+(qty>=99?'disabled':'')+'>＋</button></span><span class="cart-item-total">'+won(Number(item.price||0)*qty)+'</span></div>'+(qty>1?'<div class="cart-unit-price">개당 '+won(item.price)+'</div>':'')+'<button type="button" class="cart-product-link" data-plan-product-url="'+esc(item.product?.purchase_url||'')+'" aria-label="'+esc(item.product?.name)+' 상품 페이지 열기">상품 페이지 ↗</button></div>'}).join('')+'</div><div class="line"></div><div class="muted">예상 합계</div><div class="sum">'+won(Number(totals.selected_price||0))+'</div><p class="muted">'+tfBudgetText(result)+'</p><button class="btn strong wide" data-action="confirm" '+(!items.length||totals.over_budget?'disabled':'')+'>이 리스트로 확정하기 →</button></aside>'}
function tfBasketAside(result){const items=(result.items||[]).filter(item=>item.selected),totals=result.totals||{};return '<aside class="panel sticky"><h2>나의 장바구니 <span class="tag">'+Number(totals.selected_units||0)+'</span></h2>'+items.map(item=>'<div class="row spread" style="margin:12px 0;font-size:14px"><span>'+esc(item.slot_label)+(Number(item.qty)>1?' × '+Number(item.qty):'')+'</span><b>'+won(Number(item.price||0)*Math.max(1,Number(item.qty)||1))+'</b></div>').join('')+'<div class="line"></div><div class="muted">예상 합계</div><div class="sum">'+won(Number(totals.selected_price||0))+'</div><p class="muted">'+tfBudgetText(result)+'</p><button class="btn strong wide" data-action="confirm" '+(!items.length||totals.over_budget?'disabled':'')+'>이 리스트로 확정하기 →</button><p class="muted">결제는 각 판매처에서 진행됩니다.</p></aside>'}
function tfResultInsights(result){const explanation=result.explanation,verification=result.verification;let html='';if(explanation)html+='<div class="notice" style="margin-bottom:12px"><strong>'+esc(explanation.status==='ready'?(explanation.headline||'추천 요약'):'추천 요약')+'</strong><br>'+esc(tfLlmText(explanation,'추천 설명을 만드는 중이에요…','추천 설명을 만들지 못했어요.'))+'</div>';if(verification&&verification.status!=='not_run')html+='<details style="margin-bottom:18px"><summary>조합 검증 '+(verification.status==='ready'?'· 신뢰도 '+esc(verification.confidence??'—'):verification.status==='failed'?'· 검증 문장을 만들지 못했어요':'· 검증 중…')+'</summary>'+(verification.status==='ready'&&(verification.issues||[]).length?(verification.issues||[]).map(issue=>'<div class="review"><strong>'+esc(issue.axis)+'</strong><p>'+esc(issue.text)+'</p></div>').join(''):'<p class="muted">'+(verification.status==='ready'?'확인된 쟁점이 없어요.':'잠시 후 다시 확인해 주세요.')+'</p>')+'</details>';return html}
function closeResultOverlay(){const dialog=flow.querySelector('.result-overlay');if(dialog?.open)dialog.close();dialog?.remove()}
function showResultOverlay(html){closeResultOverlay();flow.insertAdjacentHTML('beforeend','<dialog class="result-overlay" aria-modal="true">'+html+'</dialog>');const dialog=flow.querySelector('.result-overlay');dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>dialog.remove(),{once:true});dialog.showModal();dialog.querySelector('.result-overlay-close')?.focus()}
function tfOverlayHead(kicker,title){return '<div class="result-overlay-head"><div><span class="condition-kicker">'+kicker+'</span><h2>'+esc(title)+'</h2></div><button class="result-overlay-close" type="button" data-overlay-close aria-label="닫기">×</button></div>'}
function tfFindItem(itemId){return (tfPlan.result?.items||[]).find(item=>item.item_id===itemId)||null}
// 결과 변경 요청 공용: task(listId)를 실행하고 성공하면 응답을 반환, 실패하면 화면에 안내하고 null 반환.
async function tfResultAction(task,{errorTarget=null}={}){if(tfPlan.busy)return null;const listId=tfPlan.listId;tfPlan.busy=true;try{const data=await task(listId);if(listId!==tfPlan.listId)return null;return data}catch(err){if(tfListGone(err))return null;const target=errorTarget&&flow.querySelector(errorTarget);if(target)target.textContent=tfAuthErrorMessage(err);else toast(tfAuthErrorMessage(err));return null}finally{tfPlan.busy=false}}
function tfApplyResult(data,renderFn){if(!data)return;tfPlan.result=tfRequire(data);tfPlan.listsLoaded=false;if(renderFn)renderFn()}

// ── 공용 화면 조작(모든 flow 페이지) ──
flow.addEventListener('click',e=>{
 const reload=e.target.closest('[data-reload]');if(reload){location.reload();return}
 const toggle=e.target.closest('[data-sidebar-toggle]');if(toggle){const panel=toggle.closest('.planner-sidebar'),collapsed=panel.classList.toggle('is-collapsed');toggle.setAttribute('aria-expanded',String(!collapsed));toggle.setAttribute('aria-label',collapsed?'사이드바 열기':'사이드바 접기');toggle.title=collapsed?'사이드바 열기':'사이드바 접기';try{localStorage.setItem(SIDEBAR_STORE,collapsed?'1':'0')}catch{}return}
 const newLink=e.target.closest('[data-new-basket]');if(newLink){e.preventDefault();createNewBasket();return}
 const basketLink=e.target.closest('a[data-open-basket]');if(basketLink){if(basketLink.dataset.openBasket!==tfPlan.listId)tfSelectList(basketLink.dataset.openBasket)/* 이동은 기본 href 동작에 맡김 */;return}
 const rename=e.target.closest('[data-basket-rename]');if(rename){e.preventDefault();const item=rename.closest('.planner-saved-item'),form=item?.querySelector('[data-basket-name-form]'),link=item?.querySelector('a[data-open-basket]');if(!form)return;rename.hidden=true;if(link)link.hidden=true;form.hidden=false;const input=form.querySelector('input');input?.focus();input?.select();return}
 const cancel=e.target.closest('[data-basket-cancel]');if(cancel){const item=cancel.closest('.planner-saved-item'),form=cancel.closest('form'),link=item?.querySelector('a[data-open-basket]'),renameBtn=item?.querySelector('[data-basket-rename]');form.hidden=true;if(link)link.hidden=false;if(renameBtn)renameBtn.hidden=false;return}
 const del=e.target.closest('[data-basket-delete]');if(del){tfDeleteList(del.dataset.basketDelete);return}
 const logout=e.target.closest('[data-flow-account-logout]');if(logout){e.preventDefault();tfLogout().then(ok=>{if(ok)location.reload()});return}
 const overlayClose=e.target.closest('[data-overlay-close]');if(overlayClose){closeResultOverlay();return}
 const actionBtn=e.target.closest('[data-action]');if(actionBtn){const a=actionBtn.dataset.action;if(a==='print'){window.print();return}if(a==='download'){tfDownloadReport();return}go(a);return}
});
flow.addEventListener('submit',e=>{if(!e.target.matches('[data-basket-name-form]'))return;e.preventDefault();tfRenameList(e.target.dataset.basketNameForm,String(new FormData(e.target).get('basketName')||'').trim())});
flow.addEventListener('contextmenu',e=>{const item=e.target.closest('.planner-saved-item[data-basket-item]');if(!item)return;e.preventDefault();closeBasketContextMenu();const id=item.dataset.basketItem,menu=document.createElement('div');menu.className='basket-context-menu';menu.setAttribute('role','menu');menu.innerHTML='<button type="button" role="menuitem" data-context-rename>이름 변경</button><button type="button" role="menuitem" data-context-delete>삭제</button>';document.body.append(menu);const rect=menu.getBoundingClientRect(),left=Math.min(e.clientX,window.innerWidth-rect.width-8),top=Math.min(e.clientY,window.innerHeight-rect.height-8);menu.style.left=Math.max(8,left)+'px';menu.style.top=Math.max(8,top)+'px';basketContextMenu=menu;menu.addEventListener('click',event=>{if(event.target.closest('[data-context-rename]'))item.querySelector('[data-basket-rename]')?.click();if(event.target.closest('[data-context-delete]'))tfDeleteList(id);closeBasketContextMenu()});menu.querySelector('button')?.focus()});
let basketContextMenu=null;
function closeBasketContextMenu(){if(basketContextMenu){basketContextMenu.remove();basketContextMenu=null}}
document.addEventListener('click',e=>{if(basketContextMenu&&!basketContextMenu.contains(e.target))closeBasketContextMenu()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeBasketContextMenu()});
window.addEventListener('blur',closeBasketContextMenu);

async function tfRenameList(id,name){if(!name)return;try{const summary=tfRequire(await TF_PLAN.renameList(id,name));tfPlan.lists=(tfPlan.lists||[]).map(item=>item.list_id===id?{...item,...summary}:item);if(tfPlan.report&&tfPlan.report.list_id===id)tfPlan.report.name=summary.name||name;toast('장바구니 이름을 바꿨어요.')}catch(err){toast(tfAuthErrorMessage(err))}const aside=flow.querySelector('.planner-sidebar');if(aside)aside.outerHTML=sidebar();if(typeof tfOnListRenamed==='function')tfOnListRenamed(id)}
async function tfDeleteList(id){const list=(tfPlan.lists||[]).find(item=>item.list_id===id);if(!window.confirm('"'+(list?.name||'장바구니')+'" 장바구니를 삭제할까요?'))return;try{await TF_PLAN.deleteList(id);tfPlan.lists=(tfPlan.lists||[]).filter(item=>item.list_id!==id);tfClearResetMark(id);toast('장바구니를 삭제했습니다.');if(id===tfPlan.listId){tfSelectList(null);go('category')}else{const aside=flow.querySelector('.planner-sidebar');if(aside)aside.outerHTML=sidebar()}}catch(err){toast(tfAuthErrorMessage(err))}}
function tfDownloadReport(){if(!tfPlan.report)return;const blob=new Blob([JSON.stringify(tfPlan.report,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='truefit-report.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
